spring:
  #Configuracion para el datasource
  datasource:
    url: jdbc:h2:file:c:/h2/bbddBorrar
    username: sa
    password:

  #Configuracion para JPA
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
